// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkWQgUGqUOU8GhyNA4OyDCPtIyxTm0h8',
    appId: '1:178152595689:web:cd9c3da414a49a5a171078',
    messagingSenderId: '178152595689',
    projectId: 'ditonton-dicoding-8ab78',
    authDomain: 'ditonton-dicoding-8ab78.firebaseapp.com',
    storageBucket: 'ditonton-dicoding-8ab78.appspot.com',
    measurementId: 'G-YJ8TNLL60J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIddr4iNd6kLC2LUpI7VJNx_1Laz-HrIw',
    appId: '1:178152595689:android:917d09c629630fff171078',
    messagingSenderId: '178152595689',
    projectId: 'ditonton-dicoding-8ab78',
    storageBucket: 'ditonton-dicoding-8ab78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUUfDAsMizgOB7BkfQYqorQ8zYkkLFMc',
    appId: '1:178152595689:ios:add1d7068631e628171078',
    messagingSenderId: '178152595689',
    projectId: 'ditonton-dicoding-8ab78',
    storageBucket: 'ditonton-dicoding-8ab78.appspot.com',
    iosClientId: '178152595689-4nt3jjn4uq8f0aee67vi9ajq5vh3vuag.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
